apps/teams/urls.py
from django.urls import path
from . import views

from rest_framework import routers


app_name = 'teams'

urlpatterns = [
    path('', views.manage_teams, name='teams_home'),
    path('manage/', views.manage_teams, name='manage_teams'),
    path('manage/<path:path>', views.manage_teams, name='manage_teams'),
    path('create/', views.create_team, name='create_team'),
    # invitation acceptance views
    path('invitation/<slug:invitation_id>/', views.accept_invitation, name='accept_invitation'),
]

team_urlpatterns = ([
    # team management views
    path('', views.manage_team, name='manage_team'),
    path('delete', views.delete_team, name='delete_team'),
    path('members/<int:membership_id>', views.team_membership_details, name='team_membership_details'),
    path('members/<int:membership_id>/remove/', views.remove_team_membership, name='remove_team_membership'),
    path('invite/<slug:invitation_id>/', views.resend_invitation, name='resend_invitation'),
    path('invite/', views.send_invitation_view, name='send_invitation'),
    path('invite/cancel/<slug:invitation_id>/', views.cancel_invitation_view, name='cancel_invitation'),
], 'single_team')


# DRF config for API views (required for React Teams, implementation, optional otherwise)
router = routers.DefaultRouter()
router.register('api/teams', views.TeamViewSet)
urlpatterns += router.urls

single_team_router = routers.DefaultRouter()
single_team_router.register('api/invitations', views.InvitationViewSet)
team_urlpatterns[0].extend(single_team_router.urls)

quicdoc/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.sitemaps.views import sitemap
from django.urls import path, include
from django.views.generic import RedirectView
from django.views.i18n import JavaScriptCatalog
from drf_spectacular.views import SpectacularAPIView, SpectacularSwaggerView, SpectacularRedocView

from apps.teams.urls import team_urlpatterns as single_team_urls
from apps.subscriptions.urls import team_urlpatterns as subscriptions_team_urls
from apps.web.urls import team_urlpatterns as web_team_urls
from apps.web.sitemaps import StaticViewSitemap


sitemaps = {
    'static': StaticViewSitemap(),
}

# urls that are unique to using a team should go here
team_urlpatterns = [
    path('', include(web_team_urls)),
    path('subscription/', include(subscriptions_team_urls)),
    path('team/', include(single_team_urls)),
    path('example/', include('apps.teams_example.urls')),
]


urlpatterns = [
    # redirect Django admin login to main login page
    path('admin/login/', RedirectView.as_view(pattern_name='account_login')),
    path('admin/', admin.site.urls),
    path('i18n/', include('django.conf.urls.i18n')),
    path('jsi18n/', JavaScriptCatalog.as_view(), name='javascript-catalog'),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap'),
    path('a/<slug:team_slug>/', include(team_urlpatterns)),
    path('accounts/', include('allauth_2fa.urls')),
    path('accounts/', include('allauth.urls')),
    path('users/', include('apps.users.urls')),
    path('subscriptions/', include('apps.subscriptions.urls')),
    path('teams/', include('apps.teams.urls')),
    path('', include('apps.web.urls')),
    path('pegasus/', include('pegasus.apps.examples.urls')),
    path('pegasus/employees/', include('pegasus.apps.employees.urls')),
    path('support/', include('apps.support.urls')),
    path('celery-progress/', include('celery_progress.urls')),
    # API docs
    path('api/schema/', SpectacularAPIView.as_view(), name='schema'),
    # Optional UI - you may wish to remove one of these depending on your preference
    path('api/schema/swagger-ui/', SpectacularSwaggerView.as_view(url_name='schema'), name='swagger-ui'),
    path('api/schema/redoc/', SpectacularRedocView.as_view(url_name='schema'), name='redoc'),

    # djstripe urls - for webhooks
    path("stripe/", include("djstripe.urls", namespace="djstripe")),
    # hijack urls for impersonation
    path('hijack/', include('hijack.urls', namespace='hijack')),

    # my custom code
    path('templatedocs/', include('templatedocs.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/teams/models.py
import uuid

from django.conf import settings
from django.db import models
from django.urls import reverse
from django.utils.translation import gettext
from waffle import get_setting
from waffle.models import AbstractUserFlag, CACHE_EMPTY
from waffle.utils import keyfmt, get_cache

from apps.subscriptions.models import SubscriptionModelBase
from apps.utils.models import BaseModel
from apps.web.meta import absolute_url

from . import roles


class Team(SubscriptionModelBase, BaseModel):
    """
    A Team, with members.
    """
    name = models.CharField(max_length=100)
    slug = models.SlugField(unique=True)
    members = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='teams', through='Membership')

    # your team customizations go here.

    def __str__(self):
        return self.name

    @property
    def sorted_memberships(self):
        return self.membership_set.order_by('user__email')

    def pending_invitations(self):
        return self.invitations.filter(is_accepted=False)

    @property
    def dashboard_url(self) -> str:
        return reverse('web_team:home', args=[self.slug])


class Membership(BaseModel):
    """
    A user's team membership
    """
    team = models.ForeignKey(Team, on_delete=models.CASCADE)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    role = models.CharField(max_length=100, choices=roles.ROLE_CHOICES)
    # your additional membership fields go here.

    def __str__(self):
        return f'{self.user}: {self.team}'

    def is_admin(self) -> bool:
        return self.role == roles.ROLE_ADMIN


class Invitation(BaseModel):
    """
    An invitation for new team members.
    """
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    team = models.ForeignKey(Team, on_delete=models.CASCADE, related_name='invitations')
    email = models.EmailField()
    role = models.CharField(max_length=100, choices=roles.ROLE_CHOICES, default=roles.ROLE_MEMBER)
    invited_by = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE,
                                   related_name='sent_invitations')
    is_accepted = models.BooleanField(default=False)
    accepted_by = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE,
                                    related_name='accepted_invitations', null=True, blank=True)

    def get_url(self) -> str:
        return absolute_url(reverse('teams:accept_invitation', args=[self.id]))


class BaseTeamModel(BaseModel):
    """
    Abstract model for objects that are part of a team.

    See `teams_example` app for usage.
    """
    team = models.ForeignKey(Team, verbose_name=gettext("Team"), on_delete=models.CASCADE)

    class Meta:
        abstract = True


class Flag(AbstractUserFlag):
    """Custom Waffle flag to support usage with teams.

    See https://waffle.readthedocs.io/en/stable/types/flag.html#custom-flag-models"""
    FLAG_TEAMS_CACHE_KEY = 'FLAG_TEAMS_CACHE_KEY'
    FLAG_TEAMS_CACHE_KEY_DEFAULT = 'flag:%s:teams'

    teams = models.ManyToManyField(
        Team,
        blank=True,
        help_text=gettext('Activate this flag for these teams.'),
    )

    def get_flush_keys(self, flush_keys=None):
        flush_keys = super(Flag, self).get_flush_keys(flush_keys)
        teams_cache_key = get_setting(Flag.FLAG_TEAMS_CACHE_KEY, Flag.FLAG_TEAMS_CACHE_KEY_DEFAULT)
        flush_keys.append(keyfmt(teams_cache_key, self.name))
        return flush_keys

    def is_active(self, request, read_only=False):
        is_active = super().is_active(request, read_only)
        if is_active:
            return is_active

        if not self.pk:
            # flag not created
            return False

        team = getattr(request, 'team')
        if team:
            team_ids = self._get_team_ids()
            return team.pk in team_ids

    def _get_team_ids(self):
        cache = get_cache()
        cache_key = keyfmt(
            get_setting(Flag.FLAG_TEAMS_CACHE_KEY, Flag.FLAG_TEAMS_CACHE_KEY_DEFAULT),
            self.name
        )
        cached = cache.get(cache_key)
        if cached == CACHE_EMPTY:
            return set()
        if cached:
            return cached

        team_ids = set(self.teams.all().values_list('pk', flat=True))
        cache.add(cache_key, team_ids or CACHE_EMPTY)
        return team_ids

apps/teams/views/api_views.py
from django.shortcuts import get_object_or_404
from django.utils.translation import gettext_lazy as _
from drf_spectacular.utils import extend_schema, extend_schema_view
from rest_framework import viewsets
from rest_framework.exceptions import PermissionDenied, ValidationError as DRFValidationError

from apps.api.permissions import IsAuthenticatedOrHasUserAPIKey

from ..invitations import send_invitation
from ..models import Team, Invitation
from ..permissions import TeamAccessPermissions, TeamModelAccessPermissions
from ..roles import is_admin, is_member
from ..serializers import TeamSerializer, InvitationSerializer


@extend_schema_view(
    create=extend_schema(operation_id='teams_create'),
    list=extend_schema(operation_id='teams_list'),
    retrieve=extend_schema(operation_id='teams_retrieve'),
    update=extend_schema(operation_id='teams_update'),
    partial_update=extend_schema(operation_id='teams_partial_update'),
    destroy=extend_schema(operation_id='teams_destroy'),
)
class TeamViewSet(viewsets.ModelViewSet):
    queryset = Team.objects.all()
    serializer_class = TeamSerializer
    permission_classes = (IsAuthenticatedOrHasUserAPIKey, TeamAccessPermissions)

    def get_queryset(self):
        # filter queryset based on logged in user
        return self.request.user.teams.order_by('name')

    def perform_create(self, serializer):
        # ensure logged in user is set on the model during creation
        team = serializer.save()
        team.members.add(self.request.user, through_defaults={'role': 'admin'})


@extend_schema(
    tags=["teams"]
)
@extend_schema_view(
    create=extend_schema(operation_id='invitations_create'),
    list=extend_schema(operation_id='invitations_list'),
    retrieve=extend_schema(operation_id='invitations_retrieve'),
    update=extend_schema(operation_id='invitations_update'),
    partial_update=extend_schema(operation_id='invitations_partial_update'),
    destroy=extend_schema(operation_id='invitations_destroy'),
)
class InvitationViewSet(viewsets.ModelViewSet):
    queryset = Invitation.objects.all()
    serializer_class = InvitationSerializer
    permission_classes = (IsAuthenticatedOrHasUserAPIKey, TeamModelAccessPermissions)

    @property
    def team(self):
        team = get_object_or_404(Team, slug=self.kwargs['team_slug'])
        if is_member(self.request.user, team):
            return team
        else:
            raise PermissionDenied()

    def _ensure_team_match(self, team):
        if team != self.team:
            raise DRFValidationError('Team set in invitation must match URL')

    def _ensure_no_pending_invite(self, team, email):
        if Invitation.objects.filter(team=team, email=email, is_accepted=False):
            raise DRFValidationError({
                # this mimics the same validation format used by the serializer so it can work easily on the front end.
                'email': [
                    _('There is already a pending invitation for {}. You can resend it by clicking "Resend Invitation".').format(
                        email
                    )
                ]
            })

    def get_queryset(self):
        # filter queryset based on logged in user and team
        return self.queryset.filter(team=self.team)

    def perform_create(self, serializer):
        # ensure logged in user is set on the model during creation
        # and can access the underlying team
        team = serializer.validated_data['team']
        self._ensure_team_match(team)
        self._ensure_no_pending_invite(team, serializer.validated_data['email'])

        # unfortunately, the permissions class doesn't handle creation well
        # https://www.django-rest-framework.org/api-guide/permissions/#limitations-of-object-level-permissions
        if not is_admin(self.request.user, team):
            raise PermissionDenied()

        invitation = serializer.save(invited_by=self.request.user)
        send_invitation(invitation)

apps/teams/views/invitation_views.py
from django.contrib import messages
from django.http import HttpResponseRedirect
from django.shortcuts import render, get_object_or_404
from django.urls import reverse
from django.utils.translation import gettext_lazy as _

from ..invitations import process_invitation, clear_invite_from_session
from ..models import Invitation
from ..roles import is_member


def accept_invitation(request, invitation_id):
    invitation = get_object_or_404(Invitation, id=invitation_id)
    if not invitation.is_accepted:
        # set invitation in the session in case needed later - e.g. to redirect after login
        request.session['invitation_id'] = invitation_id
    else:
        clear_invite_from_session(request)
    if request.user.is_authenticated and is_member(request.user, invitation.team):
        messages.info(
            request,
            _("It looks like you're already a member of {team}. You've been redirected.").format(
                team=invitation.team.name
            )
        )
        return HttpResponseRedirect(reverse('web_team:home', args=[invitation.team.slug]))

    if request.method == 'POST':
        # accept invitation workflow
        if not request.user.is_authenticated:
            messages.error(request, _('Please log in again to accept your invitation.'))
            return HttpResponseRedirect(reverse('account_login'))
        else:
            if invitation.is_accepted:
                messages.error(request, _('Sorry, it looks like that invitation link has expired.'))
                return HttpResponseRedirect(reverse('web:home'))
            else:
                process_invitation(invitation, request.user)
                clear_invite_from_session(request)
                messages.success(request, _('You successfully joined {}').format(invitation.team.name))
                return HttpResponseRedirect(reverse('web_team:home', args=[invitation.team.slug]))

    return render(request, 'teams/accept_invite.html', {
        'invitation': invitation,
    })

templates/teams/accept_invite.html
{% extends "web/base.html" %}
{% load static %}
{% load i18n %}
{% block body %}
<section class="mt-7 section">
  <div class= "container">
    <div class="pg-columns pg-align-items-center">
      <div class="pg-column-one-third">
        <img class="img-fluid" src="{% static 'images/undraw/undraw_lighthouse.svg' %}" alt="{% translate "Welcome!" %}">
      </div>
      <div class="pg-column">
        {% if not invitation.is_accepted %}
          <h1 class="pg-title">{% translate "Accept Invitation?" %}</h1>
          <h2 class="pg-subtitle">
            {% blocktranslate with team_name=invitation.team.name by=invitation.invited_by.get_display_name %}
            You've been invited to join {{ team_name }} by {{ by }}.
            {% endblocktranslate %}
          </h2>
          {% if request.user.is_authenticated %}
            <form method="post">
              {% csrf_token %}
              {% if request.user.email == invitation.email %}
                <input type="submit" class="pg-button-primary" value="Accept Invitation"/>
              {% else %}
                <p >
                  {% blocktranslate with invite_email=invitation.email user_email=request.user.email  %}
                  This invitation was sent to {{ invite_email }} but you're logged in as {{ user_email }}.
                  What would you like to do?
                  {% endblocktranslate %}
                </p>
                <p class="buttons my-3">
                  <input type="submit" class="pg-button-primary" value="Accept as {{ request.user.email }}"/>
                  <a class="pg-button-secondary" href="{% url 'account_logout' %}?invitation_id={{ invitation.id }}">
                    {% translate "Sign out" %}
                  </a>
                </p>
              {% endif %}
            </form>
          {% else %}
            <p class="buttons">
              <a class="pg-button-primary" href="{% url 'account_signup' %}?invitation_id={{ invitation.id }}">
                {% translate "Create Account to Accept" %}
              </a>
            </p>
          {% endif %}
        {% else %}
          <p class="pg-subtitle">
            {% translate "Sorry, it looks like that invitation has already been accepted or expired." %}
          </p>
          <p>
            {% translate "If you think this is a mistake, ask your team administrator to invite you again!" %}
          </p>
        {% endif %}
      </div>
    </div>
  </div>
</section>
{% endblock %}

templates/teams/list_teams.html
{% extends "web/app/app_base.html" %}
{% load i18n %}
{% load static %}
{% load team_tags %}
{% block app %}
<div class="app-card">
  {% if teams %}
    <h3 class="pg-subtitle">{% translate "My Teams" %}</h3>
    <div class="table-responsive">
      <table class="table pg-table">
        <thead>
        <tr>
          <th>{% translate "Name" %}</th>
          <th/>
          <th/>
        </tr>
        </thead>
        <tbody>
        {% for team in teams %}
          <tr>
            <td>{{ team.name }}</td>
            <td><a class="link" href="{% url 'web_team:home' team.slug %}">{% translate "View Dashboard" %}</a></td>
            <td class="pg-inline-buttons pg-justify-content-end">
              <a class="pg-button-secondary mx-1" href="{% url 'single_team:manage_team' team.slug %}">
                <span class="pg-icon">
                  <i class="fa fa-gear"></i>
                </span>
                <span class="pg-hidden-mobile-inline">{% if  request.user|is_admin_of:team %}{% translate "Edit" %}{% else %}{% translate "View Details" %}{% endif %}</span>
              </a>
            </td>
          </tr>
        {% endfor %}
        </tbody>
      </table>
    </div>
    <div class="mt-2">
      <a class="pg-button-secondary" href="{% url 'teams:create_team' %}">
        <span class="pg-icon"><i class="fa fa-plus"></i></span>
        <span>{% translate "Add Team" %}</span>
      </a>
    </div>
  {% else %}
    <div>
      <div class="pg-columns">
        <div class="pg-column-one-third">
          <img alt="Nothing Here" src="{% static 'images/undraw/undraw_team.svg' %}">
        </div>
        <div class="pg-column">
          <h1 class="pg-title">{% translate "No Teams Yet!" %}</h1>
          <h2 class="pg-subtitle">{% translate "Create your first team below to get started." %}</h2>
          <p>
            <a class="pg-button-primary" href="{% url 'teams:create_team' %}">
              <span class="pg-icon"><i class="fa fa-plus"></i></span>
              <span>{% translate "Create Team" %}</span>
            </a>
          </p>
        </div>
      </div>
    </div>
  {% endif %}
</div>
{% endblock %}

templates/teams/manage_team.html
{% extends "web/app/app_base.html" %}
{% load static %}
{% load i18n %}
{% load form_tags %}
{% block page_head %}
  <script src="https://unpkg.com/htmx.org@1.7.0" integrity="sha384-EzBXYPt0/T6gxNp0nuPtLkmRpmDBbjg6WmCUZRLXBBwYYmwAUxzlSGej0ARHX0Bo" crossorigin="anonymous" defer></script>
  <style>
    /* Adds fade out effect when invitations are canceled */
    tr.htmx-swapping td {
      opacity: 0;
      transition: opacity 1s ease-out;
    }
  </style>
{% endblock %}
{% block app %}
<section class="app-card">
  <h3 class="pg-subtitle">
    {% translate "Team Details" %}
  </h3>
  <form method="post">
    {% csrf_token %}
    {% render_form_fields team_form %}
    {% if create or request.team_membership.role == 'admin' %}
      <div class="pg-inline-buttons">
        <input class="pg-button-secondary" type="submit" value="{% translate 'Save Details' %}">
      </div>
    {% endif %}
  </form>
</section>
{% if not create %}
<section class="app-card">
  <h3 class="pg-subtitle">{% translate "Team Members" %}</h3>
  <div class='table-responsive'>
    <table class="table pg-table">
      <thead>
      <tr>
        <th>{% translate "Member" %}</th>
        <th>{% translate "Role" %}</th>
      </tr>
      </thead>
      <tbody>
      {% for membership in team.sorted_memberships.all %}
        <tr>
          <td>
            {% if request.team_membership.is_admin or request.team_membership == membership %}
              <a class="link" href="{% url 'single_team:team_membership_details' request.team.slug membership.pk %}">{{ membership.user }}</a>
            {% else %}
              {{ membership.user }}
            {% endif %}
          </td>
          <td>{{ membership.get_role_display }}</td>
        </tr>
      {% endfor %}
      </tbody>
    </table>
  </div>
</section>
{% include 'teams/components/team_invitations.html' %}
{% if request.team_membership.role == 'admin' %}
  <section class="app-card">
    <h3 class="pg-subtitle">
      {% translate "Danger Zone" %}
    </h3>
    <button class="pg-button-danger modal-opener" type="button" data-bs-toggle="modal" data-bs-target="#delete-modal">
      {% translate 'Delete Team' %}
    </button>
  </section>
  {% include 'teams/components/delete_team_modal.html' %}
{% endif %}
{% endif %}
{% endblock %}

templates/teams/team_membership_details.html
{% extends "web/app/app_base.html" %}
{% load i18n %}
{% load static %}
{% load form_tags %}
{% block app %}
<nav aria-label="breadcrumbs">
  <ol class="pg-breadcrumbs">
    <li class=""><a href="{% url 'single_team:manage_team' request.team.slug %}">{{ request.team.name }}</a></li>
    <li class="pg-breadcrumb-active" aria-current="page">{{ membership.user.get_display_name }}</li>
  </ol>
</nav>
<section class="app-card">
  <div class="pg-columns">
    <div id="profile-picture" class="pg-column-one-quarter">
      <div>
        <img class="avatar" src="{{ membership.user.avatar_url }}">
        <div class="pg-text-centered">{{ membership.user.get_display_name }}</div>
      </div>
    </div>
    <div class="pg-column">
      <div>
        <div class="pg-label">{% translate "Email" %}</div>
        <div class="pg-text-muted">{{ membership.user.email }}</div>
      </div>
      <div class="mt-2">
        <div class="pg-label">{% translate "Date Joined" %}</div>
        <div class="pg-text-muted">{{ membership.created_at }}</div>
      </div>
      <form class="mt-2" method="post">
        {% csrf_token %}
        {% render_form_fields membership_form %}
        {% if not editing_self %}
          <div class="mt-2">
            <input type="submit" class="pg-button-secondary" value="{% translate 'Update Role' %}">
          </div>
        {% else %}
          <p class="pg-help">{% translate "You are not allowed to modify your own role." %}</p>
        {% endif %}
        <hr class="my-2">
        <button class="button modal-opener pg-button-danger" type="button" data-bs-toggle="modal" data-bs-target="#remove-modal">
          {% if editing_self %}
            {% translate 'Leave Team' %}
          {% else %}
            {% translate 'Remove from Team' %}
          {% endif %}
        </button>
      </form>
    </div>
  </div>
</section>
{% include 'teams/components/remove_member_modal.html' %}
{% endblock %}