apps/users/urls.py
from django.urls import path
from . import views


app_name = 'users'
urlpatterns = [
    path('profile/', views.profile, name='user_profile'),
    path('profile/upload-image/', views.upload_profile_image, name='upload_profile_image'),
    path('api-keys/create/', views.create_api_key, name='create_api_key'),
    path('api-keys/revoke/', views.revoke_api_key, name='revoke_api_key'),
    path('logout-user/', views.logout_user, name='logout_user')
]

quicdoc/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.sitemaps.views import sitemap
from django.urls import path, include
from django.views.generic import RedirectView
from django.views.i18n import JavaScriptCatalog
from drf_spectacular.views import SpectacularAPIView, SpectacularSwaggerView, SpectacularRedocView

from apps.teams.urls import team_urlpatterns as single_team_urls
from apps.subscriptions.urls import team_urlpatterns as subscriptions_team_urls
from apps.web.urls import team_urlpatterns as web_team_urls
from apps.web.sitemaps import StaticViewSitemap


sitemaps = {
    'static': StaticViewSitemap(),
}

# urls that are unique to using a team should go here
team_urlpatterns = [
    path('', include(web_team_urls)),
    path('subscription/', include(subscriptions_team_urls)),
    path('team/', include(single_team_urls)),
    path('example/', include('apps.teams_example.urls')),
]


urlpatterns = [
    # redirect Django admin login to main login page
    path('admin/login/', RedirectView.as_view(pattern_name='account_login')),
    path('admin/', admin.site.urls),
    path('i18n/', include('django.conf.urls.i18n')),
    path('jsi18n/', JavaScriptCatalog.as_view(), name='javascript-catalog'),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap'),
    path('a/<slug:team_slug>/', include(team_urlpatterns)),
    path('accounts/', include('allauth_2fa.urls')),
    path('accounts/', include('allauth.urls')),
    path('users/', include('apps.users.urls')),
    path('subscriptions/', include('apps.subscriptions.urls')),
    path('teams/', include('apps.teams.urls')),
    path('', include('apps.web.urls')),
    path('pegasus/', include('pegasus.apps.examples.urls')),
    path('pegasus/employees/', include('pegasus.apps.employees.urls')),
    path('support/', include('apps.support.urls')),
    path('celery-progress/', include('celery_progress.urls')),
    # API docs
    path('api/schema/', SpectacularAPIView.as_view(), name='schema'),
    # Optional UI - you may wish to remove one of these depending on your preference
    path('api/schema/swagger-ui/', SpectacularSwaggerView.as_view(url_name='schema'), name='swagger-ui'),
    path('api/schema/redoc/', SpectacularRedocView.as_view(url_name='schema'), name='redoc'),

    # djstripe urls - for webhooks
    path("stripe/", include("djstripe.urls", namespace="djstripe")),
    # hijack urls for impersonation
    path('hijack/', include('hijack.urls', namespace='hijack')),

    # my custom code
    path('templatedocs/', include('templatedocs.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/dashboard/components/extra_scripts.html
{% load static %}

<script src="{% static 'admin/vendors/@coreui/coreui/js/coreui.bundle.min.js' %}"></script>
<script src="{% static 'admin/vendors/simplebar/js/simplebar.min.js' %}"></script>
<!-- Plugins and scripts required by this view-->
<script src="{% static 'admin/vendors/chart.js/js/chart.min.js' %}"></script>
<script src="{% static 'admin/vendors/@coreui/chartjs/js/coreui-chartjs.js' %}"></script>
<script src="{% static 'admin/vendors/@coreui/utils/js/coreui-utils.js' %}"></script>
<script src="{% static 'admin/js/main.js' %}"></script>
<script>
</script>

templates/dashboard/components/sidebar.html
{% load static %}
<div class="sidebar sidebar-dark sidebar-fixed" id="sidebar">
    <div class="sidebar-brand d-none d-md-flex">
        {#        <svg class="sidebar-brand-full" width="118" height="46" alt="CoreUI Logo">#}
        {#            <use xlink:href="{% static 'assets' %}/img/logos/logo/bulkit-square-core.svg"></use>#}
        {#        </svg>#}
        {#        <svg class="sidebar-brand-narrow" width="46" height="46" alt="CoreUI Logo">#}
        {#            <use xlink:href="{% static 'assets' %}/img/logos/logo/bulkit-square-core.svg"></use>#}
        {#        </svg>#}

        <h2 class="text-white">QuicDoc</h2>
    </div>
    <ul class="sidebar-nav" data-coreui="navigation" data-simplebar="">
        {#        <li class="nav-item"><a class="nav-link" href="/a/some/">#}
        {#        <li class="nav-item"><a class="nav-link" href="#">#}
        {#            <svg class="nav-icon">#}
        {#                <use xlink:href="{% static 'admin' %}/vendors/@coreui/icons/svg/free.svg#cil-speedometer"></use>#}
        {#            </svg>#}
        {#            Dashboard</a></li>#}
        {#        <li class="nav-title">Theme</li>#}
        <li class="nav-item"><a class="nav-link" href="{% url 'get_all' %}">
            <svg class="nav-icon">
                <use xlink:href="{% static 'admin' %}/vendors/@coreui/icons/svg/free.svg#cil-pencil"></use>
            </svg>
            Templates</a></li>


        <li class="nav-item"><a class="nav-link" href="{% url 'users:user_profile' %}">
            <svg class="nav-icon">
                <use xlink:href="{% static 'admin' %}/vendors/@coreui/icons/svg/free.svg#cil-user"></use>
            </svg>
            Profile</a></li>

        <li class="nav-item"><a class="nav-link" href="{% url 'users:logout_user' %}">
            <svg class="nav-icon">
                <use xlink:href="{% static 'admin' %}/vendors/@coreui/icons/svg/free.svg#cil-account-logout"></use>
            </svg>
            Logout</a></li>
{#        <li class="nav-item mt-auto"><a class="nav-link" href="{% url 'users:logout_user' %}">#}
{#            <svg class="icon me-2">#}
{#                <use xlink:href="{% static 'admin' %}/vendors/@coreui/icons/svg/free.svg#cil-account-logout"></use>#}
{#            </svg>#}
{#            Logout</a></li>#}
    </ul>
    <button class="sidebar-toggler" type="button" data-coreui-toggle="unfoldable"></button>
</div>

templates/dashboard/components/top_nav.html
{% load static %}

<header class="header header-sticky mb-4">
    <div class="container-fluid">
        <button class="header-toggler px-md-0 me-md-3" type="button"
                onclick="coreui.Sidebar.getInstance(document.querySelector('#sidebar')).toggle()">
            <svg class="icon icon-lg">
                <use xlink:href="{% static 'admin' %}/vendors/@coreui/icons/svg/free.svg#cil-menu"></use>
            </svg>
        </button>
        <a class="header-brand d-md-none" href="#">
            <svg width="118" height="46" alt="CoreUI Logo">
                <use xlink:href="{% static 'assets' %}/img/logos/logo/bulkit-square-core.svg"></use>
            </svg>
        </a>
        <ul class="header-nav d-none d-md-flex">
            <li class="nav-item"><a class="nav-link" href="{% url 'get_all' %}">Dashboard</a></li>
            {#            <li class="nav-item"><a class="nav-link" href="#">Users</a></li>#}
            {#            <li class="nav-item"><a class="nav-link" href="#">Settings</a></li>#}
        </ul>
        <ul class="header-nav ms-auto">
            <li class="nav-item"><a class="nav-link" href="#">
                <svg class="icon icon-lg">
                    <use xlink:href={% static 'admin' %}/vendors/@coreui/icons/svg/free.svg#cil-bell"></use>
                </svg>
            </a></li>
        </ul>
        <ul class="header-nav ms-3">
            <li class="nav-item dropdown"><a class="nav-link py-0" data-coreui-toggle="dropdown" href="#" role="button"
                                             aria-haspopup="true" aria-expanded="false">
                <div class="avatar avatar-md">
                    {% if request.user.is_authenticated %}

                        <img class="avatar-img rounded-circle"
                             src="{{ user.avatar_url}}"
                             alt="user@email.com">
                    {% endif %}
                </div>
            </a>
                <div class="dropdown-menu dropdown-menu-end pt-0">
                    <div class="dropdown-header bg-light py-2">
                        <div class="fw-semibold">Settings</div>
                    </div>
                    <a class="dropdown-item" href="/users/profile">
                        <svg class="icon me-2">
                            <use xlink:href="{% static 'admin' %}/vendors/@coreui/icons/svg/free.svg#cil-user"></use>
                        </svg>
                        Profile
                    </a>
                    {#                    <a class="dropdown-item" href="#">#}
                    {#                    <svg class="icon me-2">#}
                    {#                        <use xlink:href="{% static 'admin' %}/vendors/@coreui/icons/svg/free.svg#cil-settings"></use>#}
                    {#                    </svg>#}
                    {#                    Settings</a><a class="dropdown-item" href="#">#}
                    {#                    <svg class="icon me-2">#}
                    {#                        <use xlink:href="{% static 'admin' %}/vendors/@coreui/icons/svg/free.svg#cil-credit-card"></use>#}
                    {#                    </svg>#}
                    {#                    Payments<span class="badge badge-sm bg-secondary ms-2">42</span></a><a class="dropdown-item"#}
                    {#                                                                                           href="#">#}
                    {#                    <svg class="icon me-2">#}
                    {#                        <use xlink:href="{% static 'admin' %}/vendors/@coreui/icons/svg/free.svg#cil-file"></use>#}
                    {#                    </svg>#}
                    {#                    Projects<span class="badge badge-sm bg-primary ms-2">42</span></a>#}
                    {#                    <div class="dropdown-divider"></div>#}
                    {#                    <a class="dropdown-item" href="#">#}
                    {#                        <svg class="icon me-2">#}
                    {#                            <use xlink:href="{% static 'admin' %}/vendors/@coreui/icons/svg/free.svg#cil-lock-locked"></use>#}
                    {#                        </svg>#}
                    {#                        Lock Account</a>#}

                    <a class="dropdown-item" href="/accounts/password/change/">
                        <svg class="icon me-2">
                            <use xlink:href="{% static 'admin' %}/vendors/@coreui/icons/svg/free.svg#cil-pencil"></use>
                        </svg>
                        Change Password
                    </a>

                    <a class="dropdown-item" href="/accounts/logout">
                        <svg class="icon me-2">
                            <use xlink:href="{% static 'admin' %}/vendors/@coreui/icons/svg/free.svg#cil-account-logout"></use>
                        </svg>
                        Logout
                    </a>
                </div>
            </li>
        </ul>
    </div>
    {#    <div class="header-divider"></div>#}
    {#    <div class="container-fluid">#}
    {#        <nav aria-label="breadcrumb">#}
    {#            <ol class="breadcrumb my-0 ms-2">#}
    {#                <li class="breadcrumb-item">#}
    {#                    <!-- if breadcrumb is single--><span>Home</span>#}
    {#                </li>#}
    {#                <li class="breadcrumb-item active"><span>Dashboard</span></li>#}
    {#            </ol>#}
    {#        </nav>#}
    {#    </div>#}
</header>