apps/web/urls.py
from django.urls import path
from django.views.generic import TemplateView

from . import views

app_name = 'web'
urlpatterns = [
    path('', views.home, name='home'),
    path('terms/', TemplateView.as_view(template_name="web/terms.html"), name='terms'),
    path('404/', TemplateView.as_view(template_name='404.html'), name='404'),
    path('500/', TemplateView.as_view(template_name='500.html'), name='500'),
    path('simulate_error/', views.simulate_error),
]

team_urlpatterns = ([
    path('', views.team_home, name='home'),
], 'web_team')

quicdoc/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.sitemaps.views import sitemap
from django.urls import path, include
from django.views.generic import RedirectView
from django.views.i18n import JavaScriptCatalog
from drf_spectacular.views import SpectacularAPIView, SpectacularSwaggerView, SpectacularRedocView

from apps.teams.urls import team_urlpatterns as single_team_urls
from apps.subscriptions.urls import team_urlpatterns as subscriptions_team_urls
from apps.web.urls import team_urlpatterns as web_team_urls
from apps.web.sitemaps import StaticViewSitemap


sitemaps = {
    'static': StaticViewSitemap(),
}

# urls that are unique to using a team should go here
team_urlpatterns = [
    path('', include(web_team_urls)),
    path('subscription/', include(subscriptions_team_urls)),
    path('team/', include(single_team_urls)),
    path('example/', include('apps.teams_example.urls')),
]


urlpatterns = [
    # redirect Django admin login to main login page
    path('admin/login/', RedirectView.as_view(pattern_name='account_login')),
    path('admin/', admin.site.urls),
    path('i18n/', include('django.conf.urls.i18n')),
    path('jsi18n/', JavaScriptCatalog.as_view(), name='javascript-catalog'),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap'),
    path('a/<slug:team_slug>/', include(team_urlpatterns)),
    path('accounts/', include('allauth_2fa.urls')),
    path('accounts/', include('allauth.urls')),
    path('users/', include('apps.users.urls')),
    path('subscriptions/', include('apps.subscriptions.urls')),
    path('teams/', include('apps.teams.urls')),
    path('', include('apps.web.urls')),
    path('pegasus/', include('pegasus.apps.examples.urls')),
    path('pegasus/employees/', include('pegasus.apps.employees.urls')),
    path('support/', include('apps.support.urls')),
    path('celery-progress/', include('celery_progress.urls')),
    # API docs
    path('api/schema/', SpectacularAPIView.as_view(), name='schema'),
    # Optional UI - you may wish to remove one of these depending on your preference
    path('api/schema/swagger-ui/', SpectacularSwaggerView.as_view(url_name='schema'), name='swagger-ui'),
    path('api/schema/redoc/', SpectacularRedocView.as_view(url_name='schema'), name='redoc'),

    # djstripe urls - for webhooks
    path("stripe/", include("djstripe.urls", namespace="djstripe")),
    # hijack urls for impersonation
    path('hijack/', include('hijack.urls', namespace='hijack')),

    # my custom code
    path('templatedocs/', include('templatedocs.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/frontend/components/auth_nav.html
<div class="auth-nav-alt">
    <div class="start is-hidden-mobile">
        <a href="{% url 'web:home' %}">Home</a>
    </div>
    <div class="end">

        {% if 'login' in request.path %}
            <span class="muted-text pr-10">Don't have an account?</span>
            <a href="/accounts/signup" class="button is-rounded btn-align">Sign Up</a>
        {% elif 'signup' in request.path %}
            <span class="muted-text pr-10">Already have an account?</span>
            <a href="/accounts/login" class="button is-rounded btn-align">Login</a>
        {% else %}
            <span class="muted-text pr-10">Already have an account?</span>
            <a href="/accounts/login" class="button is-rounded btn-align">Login</a>
        {% endif %}

    </div>
</div>


{% if 'login' in request.path or 'signup' in request.path %}
    {% if messages %}
    <div class="notification is-success">
        <button class="delete"></button>
        {% for message in messages %}
            {{ message }}
        {% endfor %}
    </div>
    {% endif %}
{% endif %}

templates/frontend/components/nav_bar.html
{% load static %}
{% load i18n %}
<nav class="navbar navbar-landing is-transparent nav-dark is-fixed-top is-faded">
    <div class="container">
        <div class="navbar-brand">
            <a class="navbar-item" href="{% url 'web:home' %}">
                <img class="light-logo switcher-logo-square"
                     src="{% static 'assets/img/logos/logo/bulkit-square-core.svg' %}" width="28" height="28" alt="">
                <img class="dark-logo switcher-logo-square is-hidden"
                     src="{% static 'assets/img/logos/logo/bulkit-square-core.svg' %}" width="28" height="28" alt="">
            </a>

            <a id="navigation-trigger" class="navbar-item hamburger-btn" href="javascript:void(0);">
                        <span class="menu-toggle">
                            <span class="icon-box-toggle">
                                <span class="rotate">
                                    <i class="icon-line-top"></i>
                                    <i class="icon-line-center"></i>
                                    <i class="icon-line-bottom"></i>
                                </span>
                            </span>
                        </span>
            </a>

            <a role="button" class="navbar-burger burger" aria-label="menu" aria-expanded="false"
               data-target="navbarBasicExample">
                <span aria-hidden="true"></span>
                <span aria-hidden="true"></span>
                <span aria-hidden="true"></span>
            </a>
        </div>

        <div class="navbar-menu">
            <div class="navbar-start">
                <a href="#main-features" class="navbar-item has-hover scroll-link">
                    Features
                </a>

                <a href="#pricing" class="navbar-item has-hover scroll-link">
                    Pricing
                </a>
            </div>

            <div class="navbar-end has-hover">
                <a href="/accounts/login" class="navbar-item has-border-right">
                    Login
                </a>
                <div class="separator"></div>
                <div class="navbar-item">
                    <a href="/accounts/signup" class="button button-signup is-rounded is-bold  primary-btn">Get
                        Started</a>
                </div>
            </div>
        </div>
    </div>
</nav>

templates/frontend/components/notifications.html
{% if messages %}
    <div class="notification is-success" style="z-index: 999 !important;">
        <button class="delete"></button>
        {% for message in messages %}
            {{ message }}
        {% endfor %}
    </div>
{% endif %}

templates/frontend/components/preloader.html
<div class="pageloader"></div>
<div class="infraloader is-active"></div>